# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.creaturecrumbs.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'creaturecrumbs', 'function_path': 'animated_java:creaturecrumbs/variants/default/apply'}
execute on passengers if entity @s[tag=aj.creaturecrumbs.bone.main] run function animated_java:creaturecrumbs/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.creaturecrumbs.bone.leftpupil] run function animated_java:creaturecrumbs/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.creaturecrumbs.bone.rightpupil] run function animated_java:creaturecrumbs/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.creaturecrumbs.bone.eyes] run function animated_java:creaturecrumbs/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.creaturecrumbs.bone.rightarm] run function animated_java:creaturecrumbs/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.creaturecrumbs.bone.leftarm] run function animated_java:creaturecrumbs/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.creaturecrumbs.bone.leftleg] run function animated_java:creaturecrumbs/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.creaturecrumbs.bone.rightleg] run function animated_java:creaturecrumbs/variants/default/zzz/7