# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.creaturecrumbs.root] run return 0
execute on passengers if entity @s[tag=aj.creaturecrumbs.data] unless data entity @s {data:{rigHash: '386f28f71b9ababdfc63e199e889a370bde80ca0cc7e7a32a88cd3737c4fc861'}} on vehicle run function animated_java:creaturecrumbs/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1