# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.creaturecrumbs.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:creaturecrumbs/as_root/pre_tick
execute if entity @s[tag=aj.creaturecrumbs.animation.animation.model.walk.playing] run function animated_java:creaturecrumbs/animations/animation.model.walk/zzz/on_tick
execute if entity @s[tag=aj.creaturecrumbs.animation.animation.model.lookaround.playing] run function animated_java:creaturecrumbs/animations/animation.model.lookaround/zzz/on_tick
execute if entity @s[tag=aj.creaturecrumbs.animation.animation.model.wave.playing] run function animated_java:creaturecrumbs/animations/animation.model.wave/zzz/on_tick
execute if entity @s[tag=aj.creaturecrumbs.animation.animation.model.sit.playing] run function animated_java:creaturecrumbs/animations/animation.model.sit/zzz/on_tick
execute on passengers if entity @s[tag=aj.creaturecrumbs.data] run function animated_java:creaturecrumbs/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:creaturecrumbs/as_root/post_tick