# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.creaturecrumbs.bone.main] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_main set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.creaturecrumbs.bone.leftpupil] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftpupil set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.creaturecrumbs.bone.rightpupil] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightpupil set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.creaturecrumbs.bone.eyes] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eyes set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.creaturecrumbs.bone.rightarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.creaturecrumbs.bone.leftarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.creaturecrumbs.bone.leftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.creaturecrumbs.bone.rightleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightleg set from storage aj:uuid main.out