# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.animation.model.walk.frame dummy
scoreboard objectives add aj.animation.model.lookaround.frame dummy
scoreboard objectives add aj.animation.model.wave.frame dummy
scoreboard objectives add aj.animation.model.sit.frame dummy
execute as @e[type=item_display,tag=aj.creaturecrumbs.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:creaturecrumbs/root/on_load